[colors]
black = #101010
white = #f2f2f2
red = #ff4066
dark_red = #bb2040
green = #55aa80
dark_green = #338066
yellow = #ffcc88
dark_yellow = #cc8844
blue = #66aaaa
dark_blue = #447099
purple = #8070dd
dark_purple = 6655aa
pink = #dd77dd
dark_pink = #bb55bb

[bar/voyager]
width = 100%
height = 22px
radius = 0
dpi = 96

background = ${colors.black}
foreground = ${colors.white}
line-size = 2px
border-size = 0px
border-color = ${colors.white}
padding-left = 2
padding-right = 2
module-margin = 1
seperator = |
seperator-foreground = ${dark_red}
font-0 = DepartureMono:size=11

modules-left = xworkspaces
modules-right = memory cpu wlan eth
modules-center = date
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.black}
label-active-underline = ${colors.white}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.yellow}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.dark_red}
label-empty-padding = 1

[module/memory]
type = internal/memory
interval = 2.0
format-prefix = "mem "
format-prefix-foreground = ${colors.white}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2.0
format-prefix = "cpu "
format-prefix-foreground = ${colors.white}

#[module/wlan]
#inherit = network-base
#interface-type = wireless
#label-connected = %{F${colors.white}}%ifname%%{F-} %essid% %local_ip%

#[module/eth]
#inherit = network-base
#interface-type = wired
#label-connected = %{F${colors.white}}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1.0
time = %I:%M
date = %d-%m-%Y
label = %date% %time%
label-font = 5
label-foreground = ${white}

[settings]
screenchange-reload = true

; vim:ft=dosini
